#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'

cookbook 'php', '~> 1.5.0'
cookbook 'php-fpm', '~> 0.7.0'
cookbook 'nginx', '~> 2.7.4'
cookbook 'mysql', '~> 5.6.1'
cookbook 'composer', '~> 1.0.6'
cookbook 'redis', '~> 3.0.4'
cookbook 'memcached', '~> 1.7.2'
cookbook 'heroku', '~> 0.1.0'
cookbook 'git', '~> 4.0.2'
cookbook 'postgresql', '~> 3.4.11'
cookbook 'database', '~> 2.3.0'
cookbook 'phpmyadmin', '~> 1.0.6'
cookbook 'database', '~> 2.3.0'
